language: elm
elm:
  - elm0.19.0
elm-test: 0.19.0-rev3
elm-format: 0.8.0
 
branches:
  only:
    - master
 
cache:
  directories:
    - node_modules
 
install:
  - npm install

script:
  - elm-format --validate . && elm-test
 
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/fe3h-team-builder/
  on:
    branch: master